name = "knowledge-agent-webhook"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "knowledge-agent-messages"
database_id = "a762fdcf-2c5d-47ac-aafe-1b7d36a1122a"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "knowledge-agent-images"

[triggers]
crons = ["0 22 * * *", "0 10 * * *"]
